### ISSUE TITLE
Latest nuget package doesn't work in 3.5

### ISSUE THREAD

**Issue by rtpHarry** [cmwilliams/GoogleQRGenerator-for-.NET#1]
I just installed the nuget package but when I tried to run my website (asp.net 3.5) it failed with:

```
Could not load file or assembly 'GoogleQRGenerator' or one of its dependencies. 
This assembly is built by a runtime newer than the currently loaded runtime and cannot be 
loaded.

Description: An unhandled exception occurred during the execution of the current web request. 
Please review the stack trace for more information about the error and where it originated in the 
code.

Exception Details: System.BadImageFormatException: Could not load file or assembly 
'GoogleQRGenerator' or one of its dependencies. This assembly is built by a runtime newer than 
the currently loaded runtime and cannot be loaded.
```

Looking at the code it doesn't seem that you use any .net 4 features so I'm guessing you just forgot to target it at and older version when you built the .dll?

**Comment by rtpHarry** [comment]
Hmm just tried to import the code only to my project and it seems you do use a couple of features, some optional parameters and an extra `string.Join` overload. I have just worked around these two issues to get it up and running by adding `.ToArray()` onto the parameters and removing the optional parameters code.

**Comment by cmwilliams** [comment]
I've updated the code to run on 3.5. I'll push a nuget update today.

**Comment by cmwilliams** [comment]
Nuget package has been published. Thanks for the comment and suggestions! I appreciate it.
